package com.java.day4;

import java.util.Scanner;

public class Exceptionhandaling3 {
	public static void main(String[] args) {
		Scanner sc=new Scanner(System.in);
		
		int num=sc.nextInt();
		try {
			int res=num/0;
			try {
				int res1=num/2;
				System.out.println("result is "+res1);
			}
			catch(Exception e){
				e.printStackTrace();
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}
